bin/bl-menu: add Wayland menu, rewrite to allow menu commands with arguments

diff --git a/bin/bl-menu b/bin/bl-menu
--- a/bin/bl-menu
+++ b/bin/bl-menu
@@ -1,27 +1,40 @@
 #!/bin/sh
 
-# small wrapper to launch right menu for x11 or wayland
+# small wrapper to launch a suitable BunsenLabs menu for x11 or wayland
 
-x11_menu=jgmenu_run
-wayland_menu=''
+# requires jgmenu to be installed
+x11_menu() {
+    jgmenu_run
+}
+# requires wtype, and labwc root-menu to be launched by W-Space in rc.xml
+wayland_menu() {
+    wtype -M logo -k Space
+}
+
+check_command() {
+    command -v $1 >/dev/null || {
+        echo "${0}: ${1} not found" >&2
+        exit 1
+    }
+}
 
 # BUNSEN_SESSION_TYPE is exported by bunsenlabs-session
 case $BUNSEN_SESSION_TYPE in
 x11)
-    menucmd=$x11_menu
+    check_command jgmenu_run
+    menu_function=x11_menu
     ;;
 wayland)
-    menucmd=$wayland_menu
+    check_command wtype
+    menu_function=wayland_menu
     ;;
 *)
-    echo "$0: unexpected session type: $BUNSEN_SESSION_TYPE" >&2
+    echo "${0}: unexpected session type: $BUNSEN_SESSION_TYPE" >&2
     exit 1
     ;;
 esac
 
-[ -z "$menucmd" ] && {
-    echo "$0: no $menucmd is set for session type: $BUNSEN_SESSION_TYPE" >&2
+"$menu_function" || {
+    echo "${0}: failed to execute function $menu_function" >&2
     exit 1
 }
-
-exec "$menucmd"
