bunsenlabs-session: first boot: merge ~/.Xresources and update user-dirs

diff --git a/bin/bunsenlabs-session b/bin/bunsenlabs-session
--- a/bin/bunsenlabs-session
+++ b/bin/bunsenlabs-session
@@ -12,6 +12,7 @@ usr_autostart="$usr_confdir/bunsen/autostart"
 usr_envfile="$usr_confdir/bunsen/environment"
 usr_setupflagfile="$usr_confdir/bunsen/bl-setup"
 usr_xsessionrc="$HOME/.xsessionrc"
+usr_resources="$HOME/.Xresources"
 
 default_autostart='/usr/share/bunsen/skel/.config/bunsen/autostart'
 bl_autostart='/usr/lib/bunsen/configs/bunsen-autostart'
@@ -21,6 +22,7 @@ xprop -root -remove _NET_NUMBER_OF_DESKTOPS \
       -remove _NET_DESKTOP_NAMES \
       -remove _NET_CURRENT_DESKTOP 2> /dev/null
 
+# This section is only executed on first boot.
 if [ ! -e "$usr_setupflagfile" ]
 then
     # Import user config files
@@ -28,10 +30,23 @@ then
     then
         /usr/lib/bunsen/configs/bl-user-setup --install || true
     fi
-    # Set up the user environment for X sessions;
-    # only needed on first boot, when ~/.xsessionrc is new.
-    # (Otherwise it is sourced by /etc/X11/Xsession.d/40x11-common_xsessionrc)
+    # Actions here are usually handled by scripts in /etc/X11/Xsession.d/
+    # but on first boot, user config files were not yet imported at that point.
+    # This makes a difference to the live session, unless user logs out/in.
+
+    # Merge ~/.Xresources
+    # (usually done by /etc/X11/Xsession.d/30x11-common_xresources)
+    test -r "$usr_resources" && xrdb -merge "$usr_resources" || echo "$0: cannot merge $usr_resources" >&2
+
+    # Set up the user environment for X sessions.
+    # (usually sourced by /etc/X11/Xsession.d/40x11-common_xsessionrc)
     test -r "$usr_xsessionrc" && . "$usr_xsessionrc" || echo "$0: cannot source $usr_xsessionrc" >&2
+
+    # Set up user directories
+    # (usually run by /etc/X11/Xsession.d/60xdg-user-dirs-update)
+    if [ -x /usr/bin/xdg-user-dirs-update ]; then
+        /usr/bin/xdg-user-dirs-update
+    fi
 fi
 
 # Set up the BL-specific environment.
