Rework session files to better handle Wayland

diff --git a/bunsen-autostart b/bunsen-autostart
--- a/bunsen-autostart
+++ b/bunsen-autostart
@@ -21,3 +21,11 @@ fi
 # Check for updates to contents of /usr/share/bunsen/skel
 # (Later, possibly move this to $usr_autostart. )
 bl-user-setup --auto
+
+# Under Wayland, .Xresources cannot be merged before the compositor has started
+# and anyway will only apply to xwayland windows, such as urxvt.
+# (Later, move this to $usr_autostart. )
+usr_resources="$HOME/.Xresources"
+if [ "$BUNSEN_SESSION_TYPE" = 'wayland' ]; then
+    test -r "$usr_resources" && xrdb -merge "$usr_resources" || echo "$0: cannot merge $usr_resources" >&2
+fi
